import pandas as pd
import numpy as np

# Automated fixes generated by HashPrep
def apply_fixes(df):
    df = df.copy()
    # Fix for missing_values in Cabin
    df.drop(columns=['Cabin'], inplace=True)
    # Fix for high_cardinality in Name
    # Consider target encoding or grouping rare categories for 'Name'
    # from sklearn.preprocessing import TargetEncoder
    # Fix for high_cardinality in Ticket
    # Consider target encoding or grouping rare categories for 'Ticket'
    # from sklearn.preprocessing import TargetEncoder
    # Fix for outliers in SibSp
    # Consider capping or removing outliers in 'SibSp'
    # q_low = df['SibSp'].quantile(0.01)
    # q_hi  = df['SibSp'].quantile(0.99)
    # df = df[(df['SibSp'] < q_hi) & (df['SibSp'] > q_low)]
    # Fix for outliers in Parch
    # Consider capping or removing outliers in 'Parch'
    # q_low = df['Parch'].quantile(0.01)
    # q_hi  = df['Parch'].quantile(0.99)
    # df = df[(df['Parch'] < q_hi) & (df['Parch'] > q_low)]
    # Fix for outliers in Fare
    # Consider capping or removing outliers in 'Fare'
    # q_low = df['Fare'].quantile(0.01)
    # q_hi  = df['Fare'].quantile(0.99)
    # df = df[(df['Fare'] < q_hi) & (df['Fare'] > q_low)]
    return df